### ISSUE TITLE
App setup

### ISSUE THREAD

**Issue by KlugeCh** [software-developer-org/website#6]
- install Node.js
- install express.js
- install and configure ESLint
- install and configure Prettier
- configure gitignore
- install and configure Jest for unit tests
- install and configure Playwright for e2e tests
- add README
- deploy simple app 'hello world' to google cloud

**Comment by taitruong** [comment]
For deploying node app please refer to #1

**Comment by KlugeCh** [comment]
Done.

**Comment by KlugeCh** [comment]
Reopen for fixing:
- linter problems
- add *.ts to linter rules
- adding commands scripts to package.json
- improve README.md with commands for running scripts
- added description and link for css-grid to style.css
- improved README.md with instructions to display about + impressum page

**Comment by KlugeCh** [comment]
Fixes completed. Done.
